### ISSUE TITLE
Use `theme` instead of `style` prop

### ISSUE THREAD

**Issue by nikgraf** [FormidableLabs/builder-victory-component#33]
This would be breaking change. The reason for this is that style already has a meaning for React elements and many React components follow the same pattern. Having a property `style` that behaves differently for victory components than the established standard your life as a developer gets harder.

Why `theme`? The original proposal came from @markdalgleish here: [react-themeable](https://github.com/markdalgleish/react-themeable).

**Comment by boygirl** [comment]
Hi @nikgraf thanks for this issue. It is a good discussion for us to have, and decide on while we're still in Alpha and pretty willing to break things :smile:  Could you please open it on the [main victory repo](https://github.com/FormidableLabs/victory) instead? This repo is only for infrastructure.
