### ISSUE TITLE
Update `lodash-webpack-plugin`

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/builder-victory-component#60]
0.7.0

**Comment by jdalton** [comment]
@boygirl
Can you point me to where Lodash is used. It may help me find more places
to optimize `lodash-webpack-plugin`.

**Comment by boygirl** [comment]
@jdalton thanks! This package is the archetype that controls all the infrastructure for individual Victory components like this one https://github.com/FormidableLabs/victory-chart. We're using maybe a dozen lodash methods across all the victory components. All the components are using named imports from lodash. Let me know if you need any more information. Thanks for constantly improving lodash :)

**Comment by jdalton** [comment]
Nice, thank you!
It looks like y'all are hitting most of the replacement paths for `lodash-webpack-plugin`, rock!
