### ISSUE TITLE
Use babel-preset-es2015 instead of babel-preset-es2015-webpack

### ISSUE THREAD

**Issue by thibmaek** [FormidableLabs/builder-victory-component#73]
`npm WARN deprecated babel-preset-es2015-webpack@6.4.3: Use preset options to disable module transformation https://github.com/gajus/babel-preset-es2015-webpack#deprecated`

Couldn't find any use for babel-preset-es2015-webpack in this repo so my guess is that this is just a lingering package that once was installed?

**Comment by boygirl** [comment]
@thibmaek this repo provides dependencies for other packages, so I'll have to double check it's usage. I'll definitely update to a non-deprecated preset though! Thanks

**Comment by thibmaek** [comment]
Great! This is the recommended way as per babel's latest version:

``` json
"presets": [
    ["es2015", {"modules": false}],
    "stage-2",
    "react"
],
```

**Comment by boygirl** [comment]
closed by https://github.com/FormidableLabs/builder-victory-component/pull/75
