### ISSUE TITLE
But what is Victory?

### ISSUE THREAD

**Issue by bukzor** [FormidableLabs/builder-victory-component#94]
I can't figure it out from your readme, and of course googling for "victory" doesn't give me anything useful.

**Comment by boygirl** [comment]
@bukzor I'm really surprised that you managed to find this repo in isolation. This package is only consumed internally for providing infrastructure to Victory components.  [Victory](https://github.com/FormidableLabs/victory) is a collection of charting components for React. It is broken up into multiple repos, and we use a [Builder](https://github.com/FormidableLabs/builder) workflow along with this archetype to provide consistent infrastructure across Victory components.

**Comment by bukzor** [comment]
This repo is linked from the Builder site's front page in isolation: http://formidable.com/open-source/builder/

The Builder README actually does provide a link to Victory.
